services:
  evently.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=ec0e7a21-9bfb-44df-a438-c77575496ab9
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/home/app/.aspnet/https/aspnetapp.pfx
    volumes:
      - ${USERPROFILE}/.aspnet/https:/home/app/.aspnet/https:ro