apiVersion: v1
kind: Service
metadata:
  labels:
    service: eventlydatabase
  name: eventlydatabase
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    service: eventlydatabase
