apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: eventlydatabase-claim0
  name: eventlydatabase-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
