apiVersion: v1
kind: Service
metadata:
  labels:
    service: eventlyapi
  name: eventlyapi
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 8000
    - name: "5001"
      port: 5001
      targetPort: 8081
  selector:
    io.kompose.service: eventlyapi
